# Generated by Django 5.2.17 on 2026-09-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_variantattributevalue'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_stocks_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='chk_stocks_reserved_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 0)), name='chk_stocks_minimum_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='chk_stocks_reserved_less_than_quantity'),
        ),
    ]
