# Generated by Django 5.2.17 on 2026-09-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('pk', models.CompositePrimaryKey('product_id', 'category_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='catalog.category')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='catalog.product')),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
    ]
