# Generated by Django 5.2.17 on 2026-09-07 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('attribute', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attribute')),
            ],
            options={
                'db_table': 'attribute_values',
                'ordering': ['value'],
                'constraints': [models.UniqueConstraint(fields=('attribute', 'value'), name='uq_attribute_value')],
            },
        ),
    ]
