# Generated by Django 5.2.17 on 2026-09-07 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('pk', models.CompositePrimaryKey('variant_id', 'attribute_value_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('attribute_value', models.ForeignKey(db_column='attribute_value_id', on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_values', to='catalog.attributevalue')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_values', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'variant_attribute_values',
            },
        ),
    ]
